name: Publish
on:
  push:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Bogdanp/setup-racket@v1.8.1
        with:
          architecture: 'x64'
          variant: 'CS'
          version: 'stable'
      - name: Build
        run: |
          raco pkg install --auto --user req
          make install
          make build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          publish_branch: master
